# Configuration for testing linear probing on Imagenette

# -- Data Settings --
data:
  # This path points to the dataset downloaded by download_data.py
  root_dir: downstrean-dinov3/data/imagenette2
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  input_size: 224

# -- Model Settings --
model:
  # Using the smallest distilled backbone for testing
  backbone_name: dinov3_vits16
  # Imagenette has 10 classes
  num_classes: 10
  feature_source: 'cls_patch_avg'

# -- Training Settings --
training:
  # Safe batch size for 8GB VRAM
  batch_size: 32
  # Fewer epochs for a quick test
  epochs: 10
  num_workers: 4
  device: 'cuda'

# -- Optimizer Settings --
optimizer:
  name: 'sgd'
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0

# -- Scheduler Settings --
scheduler:
  name: 'cosine'

# -- Logging and Checkpointing --
logging:
  output_dir: ./output/classification/dinov3_vits16_imagenette
  print_freq: 10
