# Default configuration for ImageNet Linear Probing

# -- Data Settings --
data:
  # IMPORTANT: Change this to the root directory of your ImageNet dataset
  root_dir: /path/to/imagenet
  # Standard ImageNet normalization values
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  # Input size for the model
  input_size: 224

# -- Model Settings --
model:
  # DINOv3 backbone architecture
  # Options: dinov3_vits16, dinov3_vitb14, dinov3_vitl16, etc.
  backbone_name: dinov3_vitb14
  # Number of classes in the dataset (ImageNet-1K has 1000)
  num_classes: 1000
  # Feature to use for the linear head. Options: 'cls', 'patch_avg', 'cls_patch_avg'
  feature_source: 'cls_patch_avg'

# -- Training Settings --
training:
  # Batch size per GPU
  batch_size: 256
  # Number of training epochs
  epochs: 90
  # Number of workers for the data loader
  num_workers: 8
  # Device to train on. 'cuda' or 'cpu'
  device: 'cuda'

# -- Optimizer Settings --
optimizer:
  # Optimizer to use. Options: 'sgd', 'adamw'
  name: 'sgd'
  # Learning rate
  lr: 0.01
  # SGD momentum
  momentum: 0.9
  # Weight decay
  weight_decay: 0.0 # No weight decay for linear probing

# -- Scheduler Settings --
scheduler:
  # Learning rate scheduler. Options: 'cosine', 'step', 'none'
  name: 'cosine'
  # For StepLR: The epoch at which to decay the learning rate
  # decay_step: 30
  # For StepLR: The factor to decay the learning rate by
  # decay_factor: 0.1

# -- Logging and Checkpointing --
logging:
  # Directory to save checkpoints and logs
  output_dir: ./output/classification/dinov3_vitb14_linear_probe
  # Print frequency (in number of batches)
  print_freq: 10
