# Default configuration for ADE20K Segmentation with DinoV3-UNet

# -- Data Settings --
data:
  # IMPORTANT: Change this to the root directory of your ADE20K dataset
  root_dir: data/ade20k
  # Standard ImageNet normalization values are often used
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  # Input size for the model. Must be a multiple of the patch size (e.g., 16).
  input_size: 256

# -- Model Settings --
model:
  # DINOv3 backbone architecture
  backbone_name: dinov3_vits16 # Using smaller backbone for less memory usage
  # Number of classes in ADE20K is 150
  num_classes: 150
  skip_connection_layers: [2, 5, 8, 11]

# -- Training Settings --
training:
  # Batch size per GPU. Reduce if you encounter memory issues.
  batch_size: 4
  epochs: 100
  num_workers: 2
  device: 'cuda'

# -- Optimizer Settings --
optimizer:
  # AdamW is generally a good choice for segmentation tasks
  name: 'adamw'
  lr: 0.0001
  weight_decay: 0.0001

# -- Scheduler Settings --
scheduler:
  name: 'cosine'

# -- Loss Settings --
loss:
  # Loss function combination. Options: 'ce', 'dice', 'ce_dice'
  name: 'ce_dice'
  # Weight for the Cross-Entropy part of the loss
  ce_weight: 0.5
  # Weight for the Dice part of the loss
  dice_weight: 0.5

# -- Logging and Checkpointing --
logging:
  output_dir: ./output/segmentation/dinov3_vits16_dpt_ade20k
  print_freq: 50
