# Configuration for MRI Head 2D Segmentation Task

# --- Data Settings ---
data:
  root_dir: "data/ade20k"
  dataset_name: "ade20k"  # Custom field to identify the dataset
  input_size: 384

# --- Model Settings ---
model:
  model_type: "unet"  # NEW: Choose 'dpt' or 'unet_full'
  backbone_name: "dinov3_vits16" # Using ViT-S as a default, can be changed
  num_classes: 2 # As specified: background + foreground
  
  # For DinoV3_UNet_Full (when model_type: "unet_full")
  decoder_channels: [256, 128, 64, 32]  # UNet decoder channel progression


# --- Training Settings ---
training:
  epochs: 20
  batch_size: 4 # Adjust based on your GPU memory
  num_workers: 4
  device: "cuda"
  warmup_epochs: 4

# -- Optimizer Settings --
optimizer:
  name: 'adamw'
  lr: 0.0005
  weight_decay: 0.0001

# -- Scheduler Settings --
scheduler:
  name: 'cosine'

# --- Logging and Checkpointing ---
logging:
  output_dir: "output/segmentation/dinov3_vits16_unet_mrihead"
  print_freq: 10