# Configuration for MRI Head 2D Segmentation Task

# --- Data Settings ---
data:
  root_dir: "data/MRIHead2D"
  dataset_name: "mrihead2d"  # Custom field to identify the dataset
  input_size: 256
  mean: [0.485, 0.456, 0.406] # Standard ImageNet mean
  std: [0.229, 0.224, 0.225]  # Standard ImageNet std

# --- Model Settings ---
model:
  model_type: "unet_full"  # NEW: Choose 'dpt' or 'unet_full'
  backbone_name: "dinov3_vits16" # Using ViT-S as a default, can be changed
  num_classes: 2 # As specified: background + foreground
  
  # For DinoV3_UNet_Full (when model_type: "unet_full")
  interaction_indexes: [2, 5, 8, 11]  # DINOv3_Adapter interaction layers
  decoder_channels: [256, 128, 64, 32]  # UNet decoder channel progression
  
  # For DinoV3_DPT (when model_type: "dpt") - backward compatibility
  skip_connection_layers: [2, 5, 8, 11] # For DPT decoder

# --- Training Settings ---
training:
  epochs: 6
  batch_size: 4 # Adjust based on your GPU memory
  num_workers: 2
  device: "cuda"
  warmup_epochs: 3

# -- Optimizer Settings --
optimizer:
  name: 'adamw'
  lr: 0.0001
  weight_decay: 0.05

# -- Scheduler Settings --
scheduler:
  name: 'cosine'

# -- Loss Settings --
loss:
  # Using combined Cross-Entropy and Dice loss by default
  name: 'ce_dice'
  ce_weight: 0.5
  dice_weight: 0.5
  # ignore_index: 255 # Optional: if you have an ignore label, specify it here.

# --- Logging and Checkpointing ---
logging:
  output_dir: "output/segmentation/dinov3_vits16_unet_full_mrihead"
  print_freq: 10